name: dsfst-vm
services:
  mongodb:
    image: mongo:6.0.13
    platform: linux/amd64
    ports:
      - target: 27017
        host_ip: "127.0.0.1"
    environment:
      MONGO_INITDB_ROOT_USERNAME: test1234
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:?Run install_dsfst.sh first}
    volumes:
      - mongodb_data:/data/db

  influxdb:
    image: influxdb:2.7
    platform: linux/amd64
    ports:
      - target: 8086
        host_ip: "127.0.0.1"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: test1234
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUX_PASSWORD:?Run install_dsfst.sh first}
      DOCKER_INFLUXDB_INIT_ORG: dsfst-org
      DOCKER_INFLUXDB_INIT_BUCKET: dsfst-bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN:?Run install_dsfst.sh first}
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2

  redis:
    image: redis:7.2.4-bookworm
    platform: linux/amd64
    ports:
      - target: 6379
        host_ip: "127.0.0.1"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - "./.dsfst/redis.conf:/usr/local/etc/redis/redis.conf:ro"

volumes:
  mongodb_data:
  influxdb_data:
  influxdb_config:
